# Generated by Django 4.1.7 on 2023-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_alter_comment_post_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
